### ISSUE TITLE
Grade fails to update in PP from Grademark (regression?)

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#82] opened 2016-02-04 06:32 UTC
Plagiarism Plugin version: 2016011102
Moodle Direct V2 version: 2016011102
Moodle Version: 2.9.3+ (Build: 20151119)

It seems the grade is not being returned to PP when updated in grademark in every case.  This was a problem about 8 months ago, though I cannot find the original issue in the tracker.  

To fix this, I have to return to grademark, click into the grade field in which an existing mark is recorded, and press enter.  The indicator at the top cycles.  After the window is closed, I wait for the PP page in Moodle to automatically update and the grade then shows up.  This was the process I used to follow previously.

Can anyone else confirm this behaviour?

**Comment by jmcgettrick** [comment] 2016-02-04 16:20
Hi @mkpelletier,
I can't reproduce this either by single grades or multiple grading. Do you receive any errors in the console? An ajax call is made when the DV closes that refreshes the page so I'm wondering if something is stopping that?

**Comment by mkpelletier** [comment] 2016-02-09 13:21
Hello John,
The problem is that this does not happen consistently, so it is hard to pin down.  I will see if I can provide more info the next time it happens.

**Comment by mhughes2k** [comment] 2016-03-14 10:30
We were able to reproduce grades not coming back to our VLE by doing the following:

1. Set up an activity
2. Submit work as student
3. Mark the work via TII
4. Setting a grade for a submission using Grademark (e.g. 50/100)
5. Closing the Grademark browser window down – grade returns immediately to Moodle
6. Go back into grademark for the submission and change the grade (e.g. 90/100) (hitting return after putting in the grade)
7. Closing down the VLE tab/window first
8. Then closing the Grademark window down
9. Then I ‘logged in as’ a student and Moodle showed the first Grade of 50
10. As the student I accessed Grademark
11. The most recent grade of 90 appeared back in Moodle after shutting down Grademark

It would seem that any scenario where the original window no longer exists or updates, means that the return of grades never occurs.

So on a related note it would be helpful if the "Refresh Submissions" option appeared in somewhere more obvious than the "Edit Settings" page for the activity. Perhaps in the Grading Actions drop down:

![image](https://cloud.githubusercontent.com/assets/694841/13741738/b37589ca-e9cf-11e5-8512-555c2477bc48.png)

**Comment by mhughes2k** [comment] 2016-03-18 10:15
Is there any reason that instead of relying on an in-browser mechanism that TII could do a server-server call back to update the data.

Afterall we have to register the use of the integrations with Turnitin and set up a shared key etc, so why couldn't the TII server use the registration information to do this, pretty vital, data exchange in a more reliable way?

It could be done by implementing a Moodle Web Service, and then we have to put the web service token & end point URL in to the TII Integration registration page.

**Comment by mhughes2k** [comment] 2016-04-07 09:57
Bumping this issue!

**Comment by mkpelletier** [comment] 2016-04-07 10:56
Thanks for the steps to recreate, @mhughes2k.  These steps work on our system as well.  The same is true of the SI after the teacher excludes matches (for example, when there is an assignment from the same student in an earlier instance of the same course, i.e. if the student failed and is retaking the course).  In this case, the original SI will display and will refuse to update with the new SI.  Perhaps these are related?

**Comment by mhughes2k** [comment] 2016-12-08 16:14
Second bump! It's coming up for 10 months! :-)

**Comment by amclarty** [comment] 2016-12-22 11:11
@mhughes2k, thanks for the updates. Apologies for the delay in responding.

I agree that a callback service is a potential solution to sending grades to the Gradebook. This would require some investigation on our part.

I'll raise this with the team and post back here once we've discussed.

**Comment by mkpelletier** [comment] 2017-01-24 07:42
This needs to be fixed.  Perhaps a suitable solution would be to call the refresh script via a cronjob at some determinate interval- hourly perhaps?

**Comment by mkpelletier** [comment] 2017-08-25 13:28
Hi all,
Is there any news on this?  This problem has not seen any progress in over a year.

**Comment by roperto** [comment] 2017-09-04 01:28
Hi. Just a bump, we are experience the same problem with our clients.

**Comment by jmcgettrick** [comment] 2017-09-05 10:42
Hi @mkpelletier and @roperto - apologies for the delay in responding.

The only way I can reproduce this is to navigate away from the inbox as @mhughes2k suggested. We do have a refresh submissions link in the assignment settings which will sync the grades up with Turnitin which is a workaround for the issue.

We will revisit callbacks but it won't be an imminent fix.

**Comment by mkpelletier** [comment] 2017-09-07 07:07
Hi John,
Thanks for the response.  I have been using the refresh script in the assignment settings, but this is not ideal.  Where can I find the script so I can call it from Cron.  This would be a much more viable option without all of the administrative overhead associated with calling it manually.

**Comment by jmcgettrick** [comment] 2017-09-12 08:19
Hi @mkpelletier - the script to update the grades is: https://github.com/turnitin/moodle-plagiarism_turnitin/blob/master/ajax.php#L74-L105. You'll need to pass in a couple of parameters; action = update_grade and the course module id.

**Closed** 2017-09-12 08:19 UTC
