### ISSUE TITLE
Cross-origin errors in Chrome

### ISSUE THREAD

**Issue by thepurpleblob** [turnitin/moodle-plagiarism_turnitin#477] opened 2019-10-22 13:16 UTC
As of Chrome 77.0.3865.90 plugin seems more-or-less broken displaying reports. The first one works but then the following ones don't open a new report. 

This seems to be an escalation of the odd behaviour where TII's javascript refreshes the Moodle assignment listing. Chrome is now stopping it doing that so it doesn't work at all.

Here's an example. Just in case it's unclear this is probably really bad!

![Screenshot 2019-10-22 at 14 07 38](https://user-images.githubusercontent.com/664139/67289411-7d11ad80-f4d6-11e9-975f-8fceface4929.png)

**Comment by dwinn** [comment] 2019-10-24 10:37
Hi @thepurpleblob,

I have just tried to reproduce this in Chrome 78.0.3904.70 (newer than yours) and it is working fine for me. I also hadn't seen any issues in Chrome 77 before updating my browser.

So that we can investigate this further, could you please create a ticket with our support team?

David.

**Comment by rboyatt** [comment] 2019-11-12 19:20
@thepurpleblob we have exactly the same issue as you're describing - first report access works but all others fail until a hard refresh of the page, with similar cross-origin errors.  Did you manage to resolve the problem?

**Comment by thepurpleblob** [comment] 2019-11-13 13:12
@rboyatt I just tried again on a completely new/vanilla version of Moodle 3.7 and turnitin. I get the cookie warning but NOT the blocked frame error. So, there's more to this than is immediately obvious. 

I need to do more testing with our live version of Moodle (lots of plugins, custom theme and so on)

**Comment by thepurpleblob** [comment] 2019-11-13 13:18
Some notes about above...

Moodle version: 3.7.3 (Build: 20191111)
plagiarism_turnitin version: 2019062501
Chrome browser version: Version 78.0.3904.70 (Official Build) (64-bit)

Moodle is completely stock. The only modification is to install the TII plagiarism plugin. All other settings are default. This is using a file uploaded to a Moodle Assignment with TII enabled. I have created a test student and a test teacher. 

Error is produced in JS console when the teacher clicks the TII link from the submissions listing.

**Comment by rboyatt** [comment] 2019-11-13 13:25
I've managed to recreate on a vanilla 3.6.3, with plagiarism_turnitin version 2019062501, Chrome 78.  

@thepurpleblob  - on 3.7.3, do you see the same behaviour with first report working but then not being able to access subsequent reports?

**Comment by thepurpleblob** [comment] 2019-11-13 13:29
@rboyatt That could be this... #424 

What you're missing (!!) is that once you have the TII window open, you're not supposed to close it. You need to navigate through your users from there. The Moodle JS sits in a loop waiting for that window to close. It then refreshes the Moodle page. On a large assignment this takes several seconds. Of course, the user doesn't know this, clicks a link and kills the XHTTP call. So the appearance is that every other one fails. 

In the nicest way, it's a really horrid bit of design.

**Comment by rboyatt** [comment] 2019-11-13 13:34
Yes! I have just been looking at the ajax.php and amd/src/open_viewer.js and come to the same conclusion!  I can completely understand that less than ideal design has confused our users (and me!)

**Comment by carl-hostrander** [comment] 2024-07-24 18:02
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.

**Closed by carl-hostrander** 2024-07-24 18:02 UTC
