### ISSUE TITLE
plagiarism_plugin::save_form_elements() is deprecated.

### ISSUE THREAD

**Issue by savva312** [turnitin/moodle-plagiarism_turnitin#536] opened 2020-08-12 10:04 UTC
Hello, running Moodle 3.9.1 and I am getting this error

Plugin version plagiarism_turnitin - 2020072201

```
plagiarism_plugin::save_form_elements() is deprecated. Use plagiarism_turnitin_coursemodule_edit_post_actions() instead
line 100 of /lib/plagiarismlib.php: call to debugging()
line 383 of /course/modlib.php: call to plagiarism_save_form_elements()
line 180 of /course/modlib.php: call to edit_module_post_actions()
line 154 of /course/modedit.php: call to add_moduleinfo()
```

**Comment by savva312** [comment] 2020-08-12 10:17
I am also seeing this one when trying to add an assigment

```
plagiarism_plugin::get_form_elements_module() is deprecated. Use plagiarism_turnitin_coursemodule_standard_elements() instead
line 131 of /lib/plagiarismlib.php: call to debugging()
line 192 of /mod/assign/mod_form.php: call to plagiarism_get_form_elements_module()
line 214 of /lib/formslib.php: call to mod_assign_mod_form->definition()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 141 of /course/modedit.php: call to moodleform_mod->__construct()
```

**Comment by danmarsden** [comment] 2020-08-13 04:45
this is a duplicate of #448

**Closed** 2021-03-04 13:32 UTC
