### ISSUE TITLE
If not fully configured plugin breaks activity edit page

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#201] opened 2016-12-08 16:12 UTC
Similar to #110 but if the plugin is not fully configured it breaks the mod_assign view.php page:

![brokenviewphp](https://cloud.githubusercontent.com/assets/694841/21017297/c8698b50-bd60-11e6-9450-aa926fb3f8cc.png)

Again in this case the Turntintooltwo plugin's Account ID & Shared key are blank, so plagiarism plugin should probably assume that it is disabled.

This turnitintooltwo v 2016091401 and Plagiarism Plugin v2016091401

**Comment by amclarty** [comment] 2016-12-22 15:36
Thanks for raising @mhughes2k.

We'll look at this and post back here with details.

**Comment by mhughes2k** [comment] 2017-05-09 08:57
Bump? Any details. This breaks things quite badly!

**Comment by dwinn** [comment] 2017-07-03 12:38
Hi @mhughes2k,

We were unable to reproduce this ourselves. I tried with a fresh environment as well as an existing one. Is there any other information you could give us?

**Comment by mhughes2k** [comment] 2017-08-01 08:33
I have also been able to reproduce this by disabling the turnitin plugin for the Forum plugin.

When you go to the forum/post.php file, it calls print_plagiarism_disclosure() which in turn calls the Turnitin print_disclose($cmid) function.

The first line of print_disclosure() goes and constructs the $tiiconnection object if it hasn't been already set up.

Within test_turnitin_connection() a new turnitin_comms class is constructed and this constructor calls turnitinttooltwo_print_error if any configure issues are found.

This print_error function has an exit() call in it which halts *all* processing of the remainder of the script.

This call probably *shouldn't* be used except in cases where the problem is unrecoverable (and in this case it's a perfectly recoverable error).

In addition the construction of the $tiiconnection should also happen *after* the plugin has checked whether or not turnitin is *actually* enabled on the module in question and not before.

**Comment by jmcgettrick** [comment] 2017-10-12 13:57
Fixed by: https://github.com/turnitin/moodle-plagiarism_turnitin/pull/273

**Comment by jmcgettrick** [comment] 2017-11-23 15:18
Fixed in 2017112302

**Closed by jmcgettrick** 2017-11-23 15:18 UTC
