### ISSUE TITLE
EULA opens in same window- UX problem

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-plagiarism_turnitin#89] opened 2016-02-18 11:05 UTC
248fbf1 seems to have created a UX problem, whereby a new user is directed in the same window as an assignment submission in the LMS.  After accepting the EULA, the user finds himself at a dead end.  The page where he started is in the history barricaded by a redirect on Turnitin's own website.  Click back just brings him back to the EULA, unless he frantically clicks back several times.  Didn't this used to all happen in a lightbox like the Rubric.  Why has this been changed to open in the same window?

**Comment by jmcgettrick** [comment] 2016-02-23 14:47
Is this still happening @mkpelletier aswe can't reproduce it?

**Comment by mkpelletier** [comment] 2016-03-02 09:21
Hello John,
This is still happening.  Please refer here to see it in action:http://www.youtube.com/watch?v=SGqXf4URXzA

**Comment by jmcgettrick** [comment] 2016-03-02 16:11
I can't reproduce this do you get a js error in firebug? I think there's maybe a conflict.

**Comment by pauln** [comment] 2016-06-01 23:18
We encountered this while testing the latest version of the plugins before rolling them out to production.  @jmcgettrick, you might have been having difficulty reproducing it because (as per the video posted by @mkpelletier) it doesn't seem to be a problem if the student accepts the EULA when first presented, but if they initially decline the EULA, upload a file to the assignment, _then_ click on the "click here to accept" link either from the submission status page or the edit submission page, it (almost always) triggers this issue.  No errors appear in the Firebug / dev tools console, which makes it a bit tricky to diagnose.

The problem is that colorbox loads the content returned from extras.php inline, instead of in an iframe; I haven't managed to determine why this happens, and it doesn't appear to have been fixed in a more recent version of colorbox.  Because that content is a form (with a JS call to submit said form), one of two things happens when it's displayed inline:
- As described here, the EULA form replaces the Moodle site, leaving the user "stuck"; or
- A different form gets submitted, because it's submitting the first form on the page (`window.document.forms[0]`); depending on the form, this can lead to a TII page opening in a new tab/window and prompting for a username/password via HTTP authentication

Although I couldn't figure out why it was happening, I did manage to find a workaround: rather than calling colorbox on the link directly, add a click handler which then triggers colorbox.  I've submitted a pull request with this fix (#148).  It may be that there's some kind of race condition happening, as various combinations of connection throttling and breakpoints seemed to "fix" it sometimes.

**Comment by dwinn** [comment] 2016-06-02 08:15
Hi @pauln,

Thanks for the extra information on how to reproduce it. I have been able to replicate this. We will get it fixed.

**Comment by pauln** [comment] 2016-06-02 09:48
Hi @dwinn, please check Pull Request #148 for a fix - I haven't been able to reproduce the issue with that in place, and it doesn't seem to cause any regressions (the EULA popup still works correctly when first seen, for instance).  The alternative invocation of colorbox used in #148 comes from colorbox's developer (in comments on a Github issue - I don't have a link handy, sorry), so it's not a 'hack' and shouldn't be in any danger of breakage - so it's probably not worth too much time/effort investigating the underlying cause further, unless you've got ideas on where to look already.

**Comment by jmcgettrick** [comment] 2016-09-14 08:25
Fixed in v2016072601.

**Closed by jmcgettrick** 2016-09-14 08:25 UTC
