### ISSUE TITLE
jQuery error: Cannot read property 'colorbox' of undefined

### ISSUE THREAD

**Issue by roperto** [turnitin/moodle-plagiarism_turnitin#182] opened 2016-10-24 23:49 UTC
Give you have an assignment with a rubric

When you are attempting to submit the assignment, I click on "View the Rubric used for marking" then I click on close (either in the top-right or in the modal form)

Then I see the following error:

view.php?id=21&action=editsubmission:1 Uncaught TypeError: Cannot read property 'colorbox' of undefined(…)onclick @ view.php?id=21&action=editsubmission:1

Example of URL:
http://moodle.test/mod/assign/view.php?id=21&action=editsubmission

Notes: Clicking outside the Modal form still works.

---

It seems like a jQuery error, it cannot find the '$' in `<a href="#" onclick="$.colorbox.close(); return false;">Close</a>`

**Comment by dwinn** [comment] 2016-10-25 08:14
Hi @roperto,

Thanks for reporting this and providing a pull request. I can confirm the behaviour you describe and we will get this fixed.

Regarding the close button on the modal itself, this is something we are aware of. The rubric manager uses an LTI launcher and the close button does not work since it is being clicked from Moodle rather than Turnitin itself (the rubric is not part of the plugin, it is loaded in an Iframe). This is why we implemented the close button in the top right of the plugin.

**Comment by roperto** [comment] 2016-10-27 01:07
Hi @dwinn 

I am not very proud of the fix I made, was a quick work around, but I will make the pull request until a better solution is found.

Cheers,

Daniel

**Comment by roperto** [comment] 2017-05-30 05:48
I am reopening this issue as it still exists in the latest release.

The PR https://github.com/turnitin/moodle-plagiarism_turnitin/pull/184 has a workaround solution for that issue.

**Comment by jmcgettrick** [comment] 2019-07-12 10:26
Closing as we no longer use colorbox.

**Closed by jmcgettrick** 2019-07-12 10:26 UTC
