### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-plagiarism_turnitin#526] opened 2020-07-15 07:56 UTC
Moodle 3.7.7
PP v2020070801

Uncaught exception 'TypeError' with message 'Argument 2 passed to has_capability() must be an instance of context, null given, called in /path/to/moodle/plagiarism/turnitin/ajax.php on line 162' in /path/to/moodle/lib/accesslib.php:427
in has_capability called at /path/to/moodle/plagiarism/turnitin/ajax.php (162)

**Comment by jmcgettrick** [comment] 2020-07-15 08:18
That's an odd one by the look of it. Is it happening on all module types for all users?

**Comment by aspark21** [comment] 2020-07-15 08:32
I've just noted two instances of that in the NewRelic logs in the last 24h so not that frequent

**Comment by aspark21** [comment] 2020-07-15 08:35
seems to have returned a 404 http status code with that. was a mod_assign

**Comment by jmcgettrick** [comment] 2020-07-15 08:53
It's happening on viewing a rubric so probably not that frequent, we'll get it looked at

**Comment by jmcgettrick** [comment] 2020-07-15 09:10
I can reproduce the issue, we'll get it fixed.

**Comment by aspark21** [comment] 2020-08-14 09:07
@jmcgettrick I didn't see this mentioned in the 2020072201 release, we are now seeing 400+ occurrences of this error on a daily basis so would be good to get this resolved. Is another release planned before the start of Academic Year?

**Comment by jmcgettrick** [comment] 2020-09-18 08:18
Closing as this is a duplicate of #537 - we'll get this fixed in the next couple of weeks

**Closed by jmcgettrick** 2020-09-18 08:18 UTC
