### ISSUE TITLE
Submissions "Pending"

### ISSUE THREAD

**Issue by mhughes2k** [turnitin/moodle-plagiarism_turnitin#115] opened 2016-03-17 09:53 UTC
We're seeing some cases where mod_assign submissions are displaying a "Pending" status for the plagiarism plugin but they don't appear to ever be coming back.

We think that the academic member of staff enabled Turnitin *after* students had started submitting items.

Would items that have already been submitted, be sent to Turnitin if it is subsequently turned on. Looking through the code I can't find a mechanism that adds them to the `turnitin_files` table unless they are actually edited and raises one of `file_uploaded`, `assessable_submitted`, `content_upload` or `files_done` events. 

The `mod_created` and `mod_updated` events do not appear to check existing for submissions.

**Comment by jmcgettrick** [comment] 2016-03-17 10:16
Hi @mhughes2k, no they wouldn't be sent in that instance, they're only sent from events.
The "pending" is - at best - confusing in that case as those are never going to be sent. 

Ideally we'd be able to work out whether there is an event for that submission that hasn't yet been processed. However, when I've looked in the past I haven't been able to work out an easy way of doing that.

**Comment by mhughes2k** [comment] 2016-03-17 11:28
The problem appears to be not that the submission hasn't been processed; it has, but it was processed *before* TII was turned on.

Given there is a "Refresh Submissions" button couldn't that simply scan Moodle assignment submissions and check if there is a corresponding turnitin_files record, and if there isn't it would indicate that the submission needs to be sent?

I've noted that Moodle appears to raise the mod_updated and mod_Created events *before* plagiarism plugins have been passed the updated / created module information, so hooking the above into these events I would presume won't work because the updated information won't have reached the plugin (see end of `edit_module_post_actions()` function in modlib.php)

**Comment by mhughes2k** [comment] 2016-03-18 09:55
The other thing that I've discovered is that I have gone in to the assign activity, reverted the submission to being a draft and re-submitted it, which has changed the timestamp, and it is logged in Moodle that I've updated the submission (so the event should have been raised)

But despite this the item is still sitting as pending, and isn't listed in the `turnititin_files` table.

**Comment by mhughes2k** [comment] 2016-03-18 09:57
Also I've asked the question about the `mod_updated` event being raised before the plagiarism plugin has been able to save the data at https://moodle.org/mod/forum/discuss.php?d=330029

**Comment by jmcgettrick** [comment] 2016-03-18 11:09
Is the resubmitted submission not raising an event in the events queue at all?

**Comment by mhughes2k** [comment] 2016-03-18 13:07
So, yesterday I reverted the submission to draft and then re-submitted it.

It would appear that the clean up function the TII plugin was then attempting to look for previous submissions for the assignment that belonged to me (because I'm the user in the eventdata), this then caused the event handler to fail, which possibly explains why the `assessable_submitted` event never completed.

We're just trying to nail this right down and we'll provide some further information...

**Comment by trevor-c** [comment] 2016-03-30 20:32
I have run into this issue as well. A moodle assignment was set up with Turnitin enabled, prior to any submissions being made.

Students have been making submissions over the last two weeks, and 9 submissions have been made successfully, but we are now seeing the pending status remain for 4 submissions. I attempted to delete a submission and re-upload it within the moodle assignment, but it remains pending for days afterward.

After reading about this issue here, I then deleted another pending submission and uploaded it as the student on the Turnitin.com side of the assignment. It was processed right away, but does not appear for the user within the assignment on the Moodle side. It appears as though the user has not made a submission from within Moodle.

I contacted support last night but haven't heard anything back yet (#00506070). To compound the problem, the assignment was intended to go into a peermark phase for the next 10 days, but a number of these submissions are still listed as pending. Is there a way to work around this?

**Comment by jmcgettrick** [comment] 2016-03-31 07:12
Hi @trevor-c are you seeing errors appear in your cron? Are these pending submissions listed in the errors table in Site Admin > Plugins > Plagiarism > Turnitin > Errors?

**Comment by trevor-c** [comment] 2016-03-31 18:06
Hi @jmcgettrick, I checked with the server admin and he hasn't noticed any errors from cron, but he doesn't generally save the output. Only one of the pending submissions was listed in the errors table. I tried resubmitting but it's still pending. 

I'll try to upgrade the plugin to see if that resolves anything.

I also heard back from support and was told uploading on the Turnitin.com side won't show up, as the submissions must originate from within Moodle. Just mentioning in case someone else reads this, as I didn't realize it was only one way.

**Comment by jmcgettrick** [comment] 2016-04-01 08:46
What plugin version are you on? 

I suspect if you check the API logs you may see an error for an assignment or a course failing to create/edit. That is usually the cause of this problem.

**Comment by trevor-c** [comment] 2016-04-01 12:52
I have just finished upgrading to the most recent version of the plugin. I didn't have anything in the API logs, so I turned on diagnostic mode and reloaded the troubled assignment. I now see log info, and the errors listed are _user_role - User already enrolled on this Class CourseSection _. Each time I reload the assignment I get about 6 more matches for this error.

The pending submissions are still listed as pending.

No pending submissions are listed in the Site Admin > Plugins > Plagiarism > Turnitin > Errors tab for this assignment.

Should I be editing the submissions or something? How do I re-trigger the upload process?

**Comment by jmcgettrick** [comment] 2016-04-01 13:14
The user already enrolled errors can be ignored, they just mean a user can't be enrolled because they already are in the class. 

Editing the submission would trigger a new event which the cron would then process.

**Comment by trevor-c** [comment] 2016-04-01 15:40
I have some cron output which suggests there is an error. Any suggestion as to why it would be an empty array?

```
Execute scheduled task: Background processing for events
... started 09:26:51. Current memory use 67.7MB.
Number of events in the Plagiarism Plugin events queue: 5806
PHP Notice:  Handler function of component plagiarism_turnitin: s:39:"plagiarism_turnitin_event_file_uploaded"; threw exception :Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays
* line 2266 of /plagiarism/turnitin/lib.php: call to moodle_database->get_in_or_equal()
* line 2370 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->clean_old_turnitin_submissions()
* line 2177 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->tii_submission()
* line 2747 of /plagiarism/turnitin/lib.php: call to plagiarism_plugin_turnitin->event_handler()
* line ? of unknownfile: call to plagiarism_turnitin_event_file_uploaded()
* line 299 of /lib/eventslib.php: call to call_user_func()
* line 343 of /lib/eventslib.php: call to events_dispatch()
* line 450 of /lib/eventslib.php: call to events_process_queued_handler()
* line 45 of /lib/classes/task/events_cron_task.php: call to events_cron()
* line 74 of /lib/cronlib.php: call to core\tas in /u01/www/production/lib/weblib.php on line 2949
... used 35 dbqueries
... used 2.1863489151001 seconds


...


Execute scheduled task: Background processing for plagiarism plugins
... started 09:26:53. Current memory use 68.6MB.
Processing cron function for plagiarism_plugin_turnitin...... started 09:26:53. Current memory use 68.6MB.
... used 3 dbqueries
... used 0.0071690082550049 seconds
Scheduled task complete: Background processing for plagiarism plugins
```

**Comment by trevor-c** [comment] 2016-04-01 16:43
I've added some debugging to see what's going on, and it appears to be failing because my user id is attached to the event, but I haven't made any submissions, so the array is empty. I have only edited the student's submission(s), and not made one myself, so shouldn't it be the students id in the event, and not mine?

I'll try to use Moodle's _login as_ ability to resubmit as the student to see if that makes any difference. Do I need to clear these entries with my user id from the mdl_events_queue?

**Comment by trevor-c** [comment] 2016-04-01 19:05
I managed to get around the issue by enrolling myself as a student and making my own submission. When cron ran again, it found a valid submission for my user id and continued to process the rest. All of the submissions now appear and have been processed as expected.

So it seems if an instructor or admin edit a submission for a student, the event should contain the student's id, and not the id of the user doing the editing.

**Comment by mhughes2k** [comment] 2016-04-04 08:07
This is the exact same scenario that I highlighted: in the case of a user other than the "actual" user triggering the events, the user that triggered it is passed about in the event data, not the user that owns the submission.

It is potentially an interesting Moodle issue, as strictly speaking it's correct that it was *me* that raised the event, but at the same time it was *for* someone else...

**Comment by jmcgettrick** [comment] 2016-04-06 11:21
Thanks @trevor-c and @mhughes2k, I can see what the problem is now. We'll get that fixed.

**Comment by dhattonturnitin** [comment] 2016-04-11 14:31
Fixed in release v2016011105

**Closed by dhattonturnitin** 2016-04-11 14:31 UTC

**Comment by dconradda** [comment] 2016-07-28 20:56
Hi there - we're using 2016011104 on moodle v3.0.2 and we have test users who are getting the Pending submission. No one has edited their submissions.

**Comment by davidmhatton** [comment] 2016-07-29 07:44
Hi @dconradda,

I see that you say that you are using version 2016011104.
The fix was in release 2016011105. I recommend upgrading your plugin to the latest version.

Kind regards

David

**Comment by dconradda** [comment] 2016-07-29 12:56
It's strange because I have another build that uses 2016011104 that works - the papers get submitted and show an Originality Score.

**Comment by davidmhatton** [comment] 2016-07-29 13:23
Hi @dconradda 

In that case it sounds like something instance specific rather than code-related. If you log a case with our support team they will be able to help you further.

Kind regards

David

**Comment by quayhealthcbd** [comment] 2019-04-05 07:53
We have here what we are expecting and this is the time for all of us to motivate us to the point that can help all of us to over view to [beat turnitin](https://www.paraphrasinguk.com/how-to-paraphrase-and-beat-turnitin/) so we can make our point to the new kicks we have.
