### ISSUE TITLE
Cannot click Close button when previewing Rubric

### ISSUE THREAD

**Issue by phil-r-openlms** [turnitin/moodle-plagiarism_turnitin#459] opened 2019-07-18 05:24 UTC
Summary:
When previewing a Rubric by clicking 'View the Rubric used for marking' the 'Close' button in the bottom right hand corner does not work. Clicking it does not close the rubric window.

Steps to replicate:
1. Create an assignment in Moodle
2. In the settings ensure turnitin plagiarism is turned on.
3 Select a rubric for the assignment (or create one and then select it if there is no rubric)
4. Save changes
5. Log in as a test student in the course, go to the assignment then click Add submission
6. Click 'View the Rubric used for marking'
7. Click the 'Close' button

Observed behaviour:
Rubric window does not close

Expected behaviour:
Rubric window closes in the same way as the 'X' (top right) and clicking out of the window.

**Comment by dwinn** [comment] 2019-07-18 07:47
Hi @philrankinBB,

Which version of the plugin are you on? We recently changed all of the modals so this shouldn't be happening any more.

**Comment by philrankinBB** [comment] 2019-07-18 08:02
Hi @dwinn our turnitin_plagiarism is on version 2019060602. Thanks.

**Comment by dwinn** [comment] 2019-07-18 08:28
Hi @philrankinBB,

Apologies, I misread. We removed a close button which existed in the top right of a modal, but the one inside the rubric itself (bottom right as you mentioned) is still there. I have just tested it on the latest version and I am able to reproduce it. I've made a ticket on our end to look into a fix.

**Comment by philrankinBB** [comment] 2019-07-31 05:52
Hi @dwinn No worries, Thanks for letting me know!

**Comment by carl-hostrander** [comment] 2024-07-24 18:01
Thank you for reporting this.  Because the latest version of the plagiarism plugin is supported for versions of Moodle 4.1 and higher, I am closing this ticket.  However, if you find this issue is occurring with the latest version of the plugin in any of the supported Moodle versions, please create a new ticket and we will address it.

**Closed by carl-hostrander** 2024-07-24 18:01 UTC
