### ISSUE TITLE
Failing unit test on Moodle 35

### ISSUE THREAD

**Issue by yao9394** [turnitin/moodle-plagiarism_turnitin#468] opened 2019-08-30 06:14 UTC
1) plagiarism_turnitin_privacy_provider_testcase::test_get_contexts_for_userid
Failed asserting that actual size 0 matches expected size 1.

/siteroot/plagiarism/turnitin/tests/privacy/provider_test.php:112
/siteroot/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "plagiarism_turnitin_privacy_provider_testcase" plagiarism/turnitin/tests/privacy/provider_test.php

FAILURES!
Tests: 5, Assertions: 29, Failures: 1.

**Comment by yao9394** [comment] 2019-08-30 07:40
Hi there,

Could anyone please review this PR? 

Thanks

**Comment by jmcgettrick** [comment] 2019-12-30 17:37
Closing as this is a duplicate of #395 

Thanks for the Pull Request though!

**Closed by jmcgettrick** 2019-12-30 17:37 UTC
